//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottonTouch
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelItemPrice
    {
        public int HIPID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> PricePerItem { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> DiscAmount { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Item Item { get; set; }
    }
}
