//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottonTouch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public Nullable<double> TotalNetAmount { get; set; }
        public Nullable<double> CarriageNet { get; set; }
        public Nullable<double> TotalTaxAmount { get; set; }
        public Nullable<double> InvoiceTotal { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
