//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottonTouch
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemServiceRequest
    {
        public int ItemServiceRequestID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> QtnSentToLaundry { get; set; }
        public Nullable<int> QtnRecievedAtLaundry { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> DiscAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
